/**
 * diary.cpp — Daily diary entries generated by LLM
 * Each entry is stored as a separate JSON file: /diary/entry_NNNN.json
 * where NNNN is a zero-padded sequential index. A small index file
 * /diary/index.json tracks the current count for fast lookups.
 * Author: Claude Code | Date: 2026-04-13
 */
#include "diary.h"
#include <ArduinoJson.h>
#include "../hal/sd_storage.h"
#include "../util/config.h"
#include "../util/debug.h"

namespace Persistence {
namespace Diary {

static const char* DIARY_DIR   = "/diary";
static const char* INDEX_PATH  = "/diary/index.json";

// Cache
static uint16_t s_count = 0;
static uint32_t s_last_entry_time = 0;
static bool     s_cache_valid = false;

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Build file path for entry at given index: /diary/entry_0000.json
static String entryPath(uint16_t index) {
    char buf[32];
    snprintf(buf, sizeof(buf), "/diary/entry_%04u.json", index);
    return String(buf);
}

/// Save index metadata to /diary/index.json
static bool saveIndex() {
    JsonDocument doc;
    doc["count"] = s_count;
    doc["last_ts"] = s_last_entry_time;

    String json;
    serializeJson(doc, json);
    return HAL::SDStorage::writeFileString(INDEX_PATH, json);
}

/// Load index metadata from /diary/index.json
static void loadIndex() {
    if (s_cache_valid) return;

    s_count = 0;
    s_last_entry_time = 0;

    String json = HAL::SDStorage::readFileString(INDEX_PATH);
    if (json.length() > 0) {
        JsonDocument doc;
        DeserializationError err = deserializeJson(doc, json);
        if (!err) {
            s_count = doc["count"] | (uint16_t)0;
            s_last_entry_time = doc["last_ts"] | (uint32_t)0;
            s_cache_valid = true;
            return;
        }
    }

    // Index file missing or corrupt — scan for entry files to rebuild
    // Check files sequentially until one is not found
    for (uint16_t i = 0; i < 9999; i++) {
        String path = entryPath(i);
        if (!HAL::SDStorage::fileExists(path.c_str())) {
            s_count = i;
            break;
        }
    }

    // Read last entry to get timestamp
    if (s_count > 0) {
        String last_path = entryPath(s_count - 1);
        String last_json = HAL::SDStorage::readFileString(last_path.c_str());
        if (last_json.length() > 0) {
            JsonDocument doc;
            if (!deserializeJson(doc, last_json)) {
                s_last_entry_time = doc["ts"] | (uint32_t)0;
            }
        }
    }

    s_cache_valid = true;
    saveIndex();

    DEBUG_LOGF("Diary: rebuilt index, %u entries found", s_count);
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

bool addEntry(const char* text, uint8_t stage) {
    loadIndex();

    HAL::SDStorage::mkdir(DIARY_DIR);

    uint32_t now = millis() / 1000;

    // Build entry JSON
    JsonDocument doc;
    doc["ts"]    = now;
    doc["stage"] = stage;
    doc["text"]  = text;

    String json;
    serializeJsonPretty(doc, json);

    // Write to /diary/entry_NNNN.json
    String path = entryPath(s_count);
    bool ok = HAL::SDStorage::writeFileString(path.c_str(), json);
    if (ok) {
        s_count++;
        s_last_entry_time = now;
        saveIndex();
        DEBUG_LOGF("Diary: wrote entry %u", s_count - 1);
    } else {
        LOG_ERROR("Diary: failed to write entry");
    }
    return ok;
}

uint16_t getCount() {
    loadIndex();
    return s_count;
}

bool getEntry(uint16_t index, DiaryEntry& out) {
    loadIndex();

    if (index >= s_count) return false;

    String path = entryPath(index);
    String json = HAL::SDStorage::readFileString(path.c_str());
    if (json.length() == 0) return false;

    JsonDocument doc;
    DeserializationError err = deserializeJson(doc, json);
    if (err) return false;

    out.timestamp = doc["ts"] | (uint32_t)0;
    out.stage     = doc["stage"] | (uint8_t)0;

    const char* t = doc["text"] | "";
    strncpy(out.text, t, sizeof(out.text) - 1);
    out.text[sizeof(out.text) - 1] = '\0';

    return true;
}

uint16_t getDiaryCount() {
    return getCount();
}

bool getDiaryEntry(uint16_t index, DiaryEntry& out) {
    return getEntry(index, out);
}

uint32_t getLastEntryTime() {
    loadIndex();
    return s_last_entry_time;
}

bool isDue() {
    uint32_t last = getLastEntryTime();
    if (last == 0) return true; // Never written — due immediately

    uint32_t now = millis() / 1000;
    float time_mult = Config::getTimeMultiplier();

    // Game-time elapsed = real elapsed * time_multiplier
    float game_elapsed = (float)(now - last) * time_mult;

    return game_elapsed >= 86400.0f; // 24h in game-time
}

} // namespace Diary
} // namespace Persistence
