/**
 * diary.h — Daily diary entries generated by LLM
 * Saved in diary.jsonl on SD card. Viewable in diary screen.
 * Author: Claude Code | Date: 2026-04-13
 */
#pragma once
#include <Arduino.h>

namespace Persistence {
namespace Diary {

    struct DiaryEntry {
        uint32_t timestamp;
        uint8_t stage;
        char text[512];
    };

    /// Append a new diary entry.
    bool addEntry(const char* text, uint8_t stage);

    /// Get entry count.
    uint16_t getCount();

    /// Read entry by index (0 = oldest). Returns false if not found.
    bool getEntry(uint16_t index, DiaryEntry& out);

    /// Get timestamp of last entry (0 if none).
    uint32_t getLastEntryTime();

    /// Check if a diary entry is due today (>24h since last).
    bool isDue();

} // namespace Diary
} // namespace Persistence
