/**
 * diary.cpp — Daily diary entries generated by LLM
 * Stores entries in diary.jsonl on SD card. Each line is a JSON object
 * with timestamp, stage, and text fields.
 * Author: Claude Code | Date: 2026-04-13
 */
#include "diary.h"
#include <ArduinoJson.h>
#include "../hal/sd_storage.h"
#include "../util/config.h"

namespace Persistence {
namespace Diary {

static const char* DIARY_PATH = "/lalien/pets/current/diary.jsonl";

// Cache last entry time to avoid re-reading file every check
static uint32_t s_last_entry_time = 0;
static bool s_cache_valid = false;

bool addEntry(const char* text, uint8_t stage) {
    uint32_t now = millis() / 1000; // approximate epoch

    JsonDocument doc;
    doc["ts"] = now;
    doc["stage"] = stage;
    doc["text"] = text;

    String line;
    serializeJson(doc, line);
    line += "\n";

    bool ok = HAL::SDStorage::appendFileString(DIARY_PATH, line);
    if (ok) {
        s_last_entry_time = now;
        s_cache_valid = true;
    }
    return ok;
}

uint16_t getCount() {
    String content = HAL::SDStorage::readFileString(DIARY_PATH);
    if (content.length() == 0) return 0;

    uint16_t count = 0;
    int pos = 0;
    while (pos < (int)content.length()) {
        int nl = content.indexOf('\n', pos);
        if (nl < 0) break;
        // Verify line is valid JSON
        if (nl > pos) count++;
        pos = nl + 1;
    }
    return count;
}

bool getEntry(uint16_t index, DiaryEntry& out) {
    String content = HAL::SDStorage::readFileString(DIARY_PATH);
    if (content.length() == 0) return false;

    uint16_t current = 0;
    int pos = 0;
    while (pos < (int)content.length()) {
        int nl = content.indexOf('\n', pos);
        if (nl < 0) break;

        if (current == index) {
            String line = content.substring(pos, nl);

            JsonDocument doc;
            DeserializationError err = deserializeJson(doc, line);
            if (err) return false;

            out.timestamp = doc["ts"] | 0;
            out.stage = doc["stage"] | 0;

            const char* text = doc["text"] | "";
            strncpy(out.text, text, sizeof(out.text) - 1);
            out.text[sizeof(out.text) - 1] = '\0';

            return true;
        }

        current++;
        pos = nl + 1;
    }

    return false; // Index out of range
}

uint32_t getLastEntryTime() {
    if (s_cache_valid) return s_last_entry_time;

    // Read last line from file
    String content = HAL::SDStorage::readFileString(DIARY_PATH);
    if (content.length() == 0) {
        s_last_entry_time = 0;
        s_cache_valid = true;
        return 0;
    }

    // Find last non-empty line
    int last_nl = -1;
    int prev_nl = -1;
    int pos = 0;
    while (pos < (int)content.length()) {
        int nl = content.indexOf('\n', pos);
        if (nl < 0) break;
        prev_nl = last_nl;
        last_nl = nl;
        pos = nl + 1;
    }

    if (last_nl < 0) {
        s_last_entry_time = 0;
        s_cache_valid = true;
        return 0;
    }

    // Extract last line
    int start = (prev_nl >= 0) ? (prev_nl + 1) : 0;
    String line = content.substring(start, last_nl);

    JsonDocument doc;
    DeserializationError err = deserializeJson(doc, line);
    if (err) {
        s_last_entry_time = 0;
    } else {
        s_last_entry_time = doc["ts"] | 0;
    }

    s_cache_valid = true;
    return s_last_entry_time;
}

bool isDue() {
    uint32_t last = getLastEntryTime();
    if (last == 0) return true; // Never written — due immediately

    uint32_t now = millis() / 1000;
    float time_mult = Config::getTimeMultiplier();

    // 24h in game-time: 86400 seconds / time_multiplier = real seconds needed
    // But since we store real timestamps and check game-time:
    // Game-time elapsed = (now - last) * time_multiplier
    float game_elapsed = (float)(now - last) * time_mult;

    return game_elapsed >= 86400.0f; // 24h in game-time
}

} // namespace Diary
} // namespace Persistence
