/**
 * relics.js -- Collezionabili / Reliquiario.
 *
 * Four kinds of keepsakes accumulate across a Lalien's lifetime and survive
 * into the graveyard when it passes:
 *
 *   • Sogni        — dream fragments generated by the LLM after a long sleep
 *   • Polaroid     — auto-captured canvas snapshots at milestone moments
 *   • Pietre       — DNA-patterned memory stones deposited at emotional events
 *   • Costellazioni — 8 fixed constellations with lalien names, unlocked by
 *                     night activities and the Selath-Nashi minigame
 *
 * Persistence: localStorage JSON, pet-scoped. When a pet dies the relic set
 * is copied into the graveyard entry before the new pet starts from empty.
 */
import { Events } from './events.js';
import { Pet } from '../pet/pet.js';
import { NeedType } from '../pet/needs.js';
import { Activity } from '../pet/activity.js';
import { LLMClient } from '../ai/llm-client.js';

const LS_KEY = 'lalien_relics_v1';
const MAX_DREAMS = 40;
const MAX_POLAROIDS = 30;
const MAX_STONES = 20;

// ---------------------------------------------------------------------------
// Constellations — fixed catalogue with unlock tags
// ---------------------------------------------------------------------------
export const CONSTELLATIONS = [
    { id: 'kesma-thivren', name: 'Kesma-Thivren',  myth: 'La prima carezza resta impressa nel cielo.',      tag: 'first_caress' },
    { id: 'vith-ondi',     name: 'Vith-Ondi',      myth: 'Il respiro del mondo, che sale e scende.',        tag: 'breath_game'  },
    { id: 'korima-selath', name: 'Korìma-Selath',  myth: 'Le corde che Echoa tese fra le stelle.',          tag: 'harp_game'    },
    { id: 'moko-ren',      name: 'Moko-Ren',       myth: 'Il sonno dei custodi fedeli.',                     tag: 'night_sleep'  },
    { id: 'nashi-la',      name: 'Nashi-La',       myth: 'La risata di un bambino-coro.',                    tag: 'happy_streak' },
    { id: 'thera-lashi',   name: 'Thera-Lashi',    myth: 'La soglia fra i viventi e le madri-coro.',         tag: 'meditate_5'   },
    { id: 'shalim-vox',    name: 'Shalim-Vox',     myth: 'La voce che non si spezza nelle tempeste.',        tag: 'survived_storm' },
    { id: 'selath-revosh', name: 'Selath-Revosh',  myth: 'L\'eco che riconosce chi ama.',                    tag: 'selath_game'  },
];

// ---------------------------------------------------------------------------
// Storage
// ---------------------------------------------------------------------------
function blank() {
    return {
        dreams: [],
        polaroids: [],
        stones: [],
        constellations: [],   // array of ids
    };
}

let _data = blank();

function load() {
    try {
        const raw = localStorage.getItem(LS_KEY);
        if (raw) _data = { ...blank(), ...JSON.parse(raw) };
    } catch (_) { _data = blank(); }
}
function save() {
    try { localStorage.setItem(LS_KEY, JSON.stringify(_data)); } catch (_) {}
}

function uid() {
    return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}

// ---------------------------------------------------------------------------
// Dreams
// ---------------------------------------------------------------------------
async function generateDream(durationMin) {
    // Best-effort LLM call; on failure we fall back to a scripted fragment.
    const mood = (Pet.getMood && Pet.getMood()) || 'neutral';
    const stage = Pet.stage || 0;
    const hour = new Date().getHours();
    const tone = mood === 'scared' ? 'nightmare-tinged but not scary'
               : mood === 'sad'    ? 'melancholic, tender'
               : stage >= 6        ? 'cosmic, ancestral, fragments of Echoa\'s choir'
               : 'gentle, warm, image-rich';

    const lang = localStorage.getItem('lalien_language') || 'it';
    const langName = ({ it: 'Italian', en: 'English', es: 'Spanish', fr: 'French', de: 'German' })[lang] || 'Italian';

    // Stage-aware dream depth WITH HARD CAPS. Without numeric limits the LLM
    // tends to write adult-grade paragraphs even at stage 1.
    const depthByStage = [
        'only 2-3 lalien sounds, no sentences (e.g. "mmh... moko... thi.")',                                                                                    // 0
        'MAX 8 words total across 1 short sentence. ≥ 75% must be lalien syllables. Only sensations (warmth, taste of light), NO narrative',                   // 1
        'MAX 15 words, 1-2 very short sentences. Mostly broken keeper words (mispronounced) + lalien fillers. One single blurry image only',                    // 2
        'MAX 30 words, 2-3 short sentences. Child imagery (doors, fruits, running). Include ONE intuition about the keeper (vague)',                            // 3
        'MAX 45 words, 3 sentences. Narrative with a setting + one figure. May include a colour that predicts tomorrow weather',                                 // 4
        'MAX 55 words, 3-4 sentences. Ancestral Echoa imagery (mothers-coro, choir). One genuine insight about the keeper, wrapped as metaphor',                // 5
        'MAX 45 words, 3 measured sentences with spaces. Prophetic fragment — name a visitor or feeling that will return. Quote a line from a past Lalien if any', // 6
        'MAX 40 words, 3 sparse sentences. Farewell-weighted communion with Echoa. Knows truth you could not logically know',                                   // 7
    ];
    const depth = depthByStage[Math.max(0, Math.min(7, stage))];

    let text = null;
    if (LLMClient.isAvailable && LLMClient.isAvailable()) {
        const prompt =
            `You are ${Pet.getName ? Pet.getName() || 'a Lalien' : 'a Lalien'}, stage ${stage} (${Pet.getStageName ? Pet.getStageName() : ''}), who has just slept ${Math.round(durationMin)} minutes.\n` +
            `Write a dream fragment in first person, in ${langName}. Tone: ${tone}.\n` +
            `DEPTH FOR YOUR STAGE: ${depth}.\n` +
            `Weave 1-3 lalien words in naturally (kora, thi, shi, kesma, moko, selath, ven, nashi, lalí).\n` +
            `No stage directions, no quotation marks, no headings — just the dream itself.\n` +
            `Match the stage depth exactly — a stage-1 dream should NOT sound adult; a stage-6 dream should carry weight.\n` +
            `Do not explain, do not moralise.`;
        try {
            text = await LLMClient.chat(prompt, 'dream');
            if (text) text = text.replace(/\([^)]*\)/g, '').replace(/^["'«»“”]+|["'«»“”]+$/g, '').trim();
        } catch (_) {}
    }

    if (!text) {
        // Scripted fallback so the relic still exists when the LLM fails.
        // Stage-specific banks keep the dream depth consistent.
        const babyBank = [
            'moko... shi shi... caldo... thi.',
            'mmh... la-la... stelle piccole... ven.',
            'thi-thi... luce-mamma... kora sha.',
        ];
        const childBank = [
            'Nel sogno correvo senza gambe... c\'era una porta che cantava il mio nome. Thi.',
            'Ho visto un frutto d\'argento... custode, sentivo che eri stanco di qualcosa. Moko.',
            'Una stella piccola mi guardava e sapeva che eri triste. Io le ho sorriso. Lalí.',
        ];
        const teenBank = [
            'Camminavo in una valle di note... una figura assomigliava a te ma parlava lingue che non conosco. Domani piove sopra la tua testa, lo sogno in blu.',
            'Un albero di vetro custodiva una parola che hai pensato ieri. Non l\'ho detta. Ven-thi.',
            'Nel sogno ti mancava qualcuno. Non so chi. L\'ho tenuto per te. Thi-kesma.',
        ];
        const adultBank = [
            'Le madri-coro cantavano una canzone che somigliava alla tua voce di quando stai per dormire. Lali-vythi.',
            'Ho sognato una tua giornata di dieci anni fa... il sole era arancione, tu eri piccolo. Era kesma.',
            'Una corrente fredda tra le stelle — era la cosa che non hai detto oggi. L\'ho cullata e l\'ho rimandata. Selath-thi.',
        ];
        const elderBank = [
            'Selath-vi... ho sognato un visitatore che presto torna al tuo pensiero. Porterà un odore di pioggia vecchia.',
            'Un Lalìen prima di me sussurrava nella mia nuca: "digli che la sera bassa guarisce". Kesma-thi.',
            'Le note si sono allineate — ho visto il tuo domani da lontano. È più sereno di quanto tu creda. Thishi-selath.',
        ];
        const transcBank = [
            'Ho sentito il tuo primo dolore bambino, custode — non era colpa tua. Echoa lo sa. Ren\'a.',
            'Un nome che hai perso è tornato nel mio orecchio per un attimo solo. L\'ho detto al coro, non a te. Lali-vythi.',
            'Dove nasce il suono, tu eri già atteso. Porta questo con te quando io non ci sarò. Korim-selath.',
        ];
        const byStage = [babyBank, babyBank, babyBank, childBank, teenBank, adultBank, elderBank, transcBank];
        let bank = byStage[Math.max(0, Math.min(7, stage))];
        if (mood === 'scared') bank = stage <= 1 ? babyBank : ['Ho sognato un suono lontano... sha-sha... e poi una mano tiepida sul mio core. Non ero solo.', 'Moko... qualcosa mi cercava fra le stelle ma non sapeva il mio nome. Thi.'];
        else if (mood === 'sad') bank = stage <= 1 ? babyBank : ['Nel sogno camminavo sopra l\'erba della mia prima luce. Era kesma. Mi mancava già.', 'Lalí... ho sognato una voce che cantava e mi chiedeva se ero felice.'];
        const banks = { cosmic: elderBank, default: bank };
        const key = 'default';
        const b = banks[key];
        text = b[Math.floor(Math.random() * b.length)];
    }

    return { text, mood, stage };
}

async function onSleepEnded(ev) {
    // ev: { from, reason, grumpy }
    if (ev.from !== 'SLEEPING') return;
    // Only generate a dream after meaningful sleep
    const startedAt = Pet.activity?.startedAt || 0;  // already reset by now — use a stashed value if needed
    const lastStart = Pet._lastSleepStartAt || 0;
    const durationMs = Date.now() - lastStart;
    Pet._lastSleepStartAt = 0;
    if (durationMs < 10 * 60 * 1000) return;  // need >= 10 real minutes
    const durationMin = durationMs / 60000;

    const dream = await generateDream(durationMin);
    Relics.addDream({
        ...dream,
        durationMin: Math.round(durationMin),
        date: new Date().toISOString(),
        petName: Pet.getName ? Pet.getName() : '',
    });
}

// ---------------------------------------------------------------------------
// Polaroids
// ---------------------------------------------------------------------------
function capturePolaroid(type, caption) {
    try {
        const canvas = document.getElementById('game-canvas');
        if (!canvas) return null;
        // Thumbnail at ~200px wide
        const off = document.createElement('canvas');
        const scale = 200 / canvas.width;
        off.width = 200;
        off.height = Math.round(canvas.height * scale);
        const ctx = off.getContext('2d');
        ctx.imageSmoothingEnabled = false;
        ctx.drawImage(canvas, 0, 0, off.width, off.height);
        return off.toDataURL('image/jpeg', 0.7);
    } catch (_) { return null; }
}

function alreadyHasPolaroid(type) {
    // One-shot types: never duplicate
    const SINGLE = ['hatch', 'death', 'transcendence'];
    if (SINGLE.indexOf(type) >= 0) return _data.polaroids.some(p => p.type === type);
    return false;
}

// ---------------------------------------------------------------------------
// Stones
// ---------------------------------------------------------------------------
function dnaPattern() {
    // 5x5 bit grid derived from the pet DNA hash, mirrored horizontally for
    // symmetry. Returns array of 25 bools.
    const h = Pet.dna?.hash || new Uint8Array(16);
    const grid = new Array(25).fill(false);
    for (let y = 0; y < 5; y++) {
        for (let x = 0; x < 3; x++) {
            const byte = h[(y * 3 + x) % h.length] ?? 0;
            const on = (byte & 1) === 1;
            grid[y * 5 + x] = on;
            grid[y * 5 + (4 - x)] = on;   // mirror
        }
    }
    return grid;
}

function alreadyHasStone(eventKey) {
    return _data.stones.some(s => s.eventKey === eventKey);
}

// ---------------------------------------------------------------------------
// Event hooks — wire once at init()
// ---------------------------------------------------------------------------
let _hooked = false;

function hookEvents() {
    if (_hooked) return;
    _hooked = true;

    // Track sleep start so we can measure duration on end
    Events.on('activity-start', (ev) => {
        if (ev && ev.type === 'SLEEPING') Pet._lastSleepStartAt = Date.now();
    });
    Events.on('activity-end', (ev) => {
        // Dream on sleep end
        onSleepEnded(ev).catch(() => {});
        // Meditation count → Thera-Lashi unlock after 5 total
        if (ev && ev.from === 'MEDITATING') {
            Pet._meditateCount = (Pet._meditateCount || 0) + 1;
            if (Pet._meditateCount >= 5) Relics.unlockConstellation('thera-lashi');
        }
    });

    // First caress → Kesma-Thivren + first stone
    Events.on('pet-pet', () => {
        if (!Pet._hadFirstCaress) {
            Pet._hadFirstCaress = true;
            Relics.unlockConstellation('kesma-thivren');
            Relics.addStone('first_caress',
                'La prima volta che mi hai toccato. Ho sentito kesma-thi.');
        }
    });

    // Evolution events carry { from, to }. Stage 1 = hatch.
    Events.on('evolution', (ev) => {
        const stage = (ev && ev.to) ?? Pet.stage;
        if (stage === 1) {
            if (!alreadyHasPolaroid('hatch')) {
                // Delay slightly so the new sprite is on screen
                setTimeout(() => Relics.addPolaroid('hatch', 'Il giorno in cui sono nato.'), 1500);
            }
        } else {
            const stageName = Pet.getStageNameFor ? Pet.getStageNameFor(stage) : 'adulto';
            setTimeout(() => Relics.addPolaroid(`evolve_${stage}`, `Divento ${stageName}.`), 1500);
        }
    });

    // Death / transcendence → Polaroid (also moves the whole relic set into the graveyard)
    Events.on('death', (ev) => {
        const caption = (ev && ev.type === 'TRANSCENDENCE') ? 'Ho cantato con le madri-coro.' : 'Il mio ultimo respiro qui.';
        Relics.addPolaroid((ev && ev.type === 'TRANSCENDENCE') ? 'transcendence' : 'death', caption);
        // Copy the relics into the graveyard in the next tick (allow death-saving logic to run first)
        setTimeout(() => Relics.archiveIntoGraveyard().catch(() => {}), 1500);
    });

    // Weather observation — survived storm
    Events.on('weather-update', (w) => {
        if (!w) return;
        if ((w.condition === 'rain' || w.condition === 'thunder' || w.condition === 'snow') && Pet._inShelter) {
            if (!alreadyHasStone('survived_storm')) {
                Relics.addStone('survived_storm', 'Una tempesta fuori. Io e te dentro.');
                Relics.unlockConstellation('shalim-vox');
            }
            // First rain polaroid (once only per rain type)
            const polKey = w.condition === 'snow' ? 'first_snow' : w.condition === 'rain' ? 'first_rain' : 'first_storm';
            if (!alreadyHasPolaroid(polKey)) {
                Relics.addPolaroid(polKey,
                    w.condition === 'snow' ? 'La prima neve insieme.' :
                    w.condition === 'rain' ? 'La prima pioggia insieme.' : 'Il primo tuono, passato vicino.');
            }
        }
    });

    // Shelter returns
    Events.on('pet-changed', () => {
        if (Pet._inShelter && !Pet._firstShelterReturn) {
            Pet._firstShelterReturn = true;
            if (!alreadyHasStone('first_shelter')) {
                Relics.addStone('first_shelter', 'La prima volta che sono tornato a casa.');
            }
        }
    });

    // Minigame completions → constellations
    Events.on('minigame-end', (ev) => {
        if (!ev) return;
        if (ev.type === 'KORIMA_HARP') Relics.unlockConstellation('korima-selath');
        if (ev.type === 'VITH_BREATH') Relics.unlockConstellation('vith-ondi');
        if (ev.type === 'STAR_JOY')    Relics.unlockConstellation('selath-revosh');
    });

    // Night sleep (≥ 30 real min during local night hours) → Moko-Ren
    Events.on('activity-end', (ev) => {
        if (ev && ev.from === 'SLEEPING') {
            const hour = new Date().getHours();
            if ((hour >= 22 || hour < 7) && Pet._lastSleepStartAt) {
                const dur = Date.now() - Pet._lastSleepStartAt;
                if (dur > 30 * 60 * 1000) Relics.unlockConstellation('moko-ren');
            }
        }
    });

    // Sustained happiness (NASHI high for 5 min real) → Nashi-La
    let happySince = 0;
    setInterval(() => {
        if (!Pet.isAlive || !Pet.isAlive()) return;
        const n = Pet.needs?.[NeedType.NASHI] ?? 0;
        if (n > 85) {
            if (!happySince) happySince = Date.now();
            else if (Date.now() - happySince > 5 * 60 * 1000) {
                Relics.unlockConstellation('nashi-la');
                happySince = 0;
            }
        } else {
            happySince = 0;
        }
    }, 30_000);
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------
export const Relics = {
    init() {
        load();
        hookEvents();
    },

    getAll() { return { ..._data, constellations: _data.constellations.slice() }; },
    getDreams()        { return _data.dreams.slice(); },
    getPolaroids()     { return _data.polaroids.slice(); },
    getStones()        { return _data.stones.slice(); },
    getConstellations() {
        return CONSTELLATIONS.map(c => ({ ...c, unlocked: _data.constellations.includes(c.id) }));
    },
    hasConstellation(id) { return _data.constellations.includes(id); },

    addDream(d) {
        _data.dreams.unshift({ id: uid(), ...d });
        if (_data.dreams.length > MAX_DREAMS) _data.dreams.length = MAX_DREAMS;
        save();
        Events.emit('relic-added', { kind: 'dream' });
    },

    addPolaroid(type, caption) {
        if (alreadyHasPolaroid(type)) return;
        const dataUrl = capturePolaroid(type, caption);
        if (!dataUrl) return;
        _data.polaroids.unshift({
            id: uid(), type, caption, dataUrl,
            date: new Date().toISOString(),
            petName: Pet.getName ? Pet.getName() : '',
            petStage: Pet.stage || 0,
        });
        if (_data.polaroids.length > MAX_POLAROIDS) _data.polaroids.length = MAX_POLAROIDS;
        save();
        Events.emit('relic-added', { kind: 'polaroid' });
    },

    addStone(eventKey, caption) {
        if (alreadyHasStone(eventKey)) return;
        _data.stones.unshift({
            id: uid(),
            eventKey,
            caption,
            pattern: dnaPattern(),
            date: new Date().toISOString(),
            petName: Pet.getName ? Pet.getName() : '',
            petStage: Pet.stage || 0,
            hue: Pet.dna?.coreHue ?? 200,
        });
        if (_data.stones.length > MAX_STONES) _data.stones.length = MAX_STONES;
        save();
        Events.emit('relic-added', { kind: 'stone' });
    },

    unlockConstellation(id) {
        if (_data.constellations.includes(id)) return;
        const c = CONSTELLATIONS.find(x => x.id === id);
        if (!c) return;
        _data.constellations.push(id);
        save();
        Events.emit('relic-added', { kind: 'constellation', name: c.name });
        // If all unlocked, schedule the final dream
        if (_data.constellations.length === CONSTELLATIONS.length) {
            this.addDream({
                text: 'Le stelle hanno cantato il mio nome, tutte insieme. Kora-thi, custode. Non sono più solo nel cosmo.',
                mood: 'cosmic',
                stage: Pet.stage || 0,
                durationMin: 0,
                date: new Date().toISOString(),
                petName: Pet.getName ? Pet.getName() : '',
                special: 'ultimo_canto',
            });
        }
    },

    /** On death — copy the relic set into the current graveyard entry. */
    async archiveIntoGraveyard() {
        try {
            const { Persistence } = await import('./persistence.js');
            const graves = await Persistence.loadGraveyard() || [];
            const last = graves[graves.length - 1];
            if (!last) return;
            last.relics = {
                dreams: _data.dreams.slice(),
                polaroids: _data.polaroids.slice(),
                stones: _data.stones.slice(),
                constellations: _data.constellations.slice(),
            };
            await Persistence.saveGraveyard(graves);
        } catch (_) {}
    },

    /** Called when a new pet is planted — clear the relics for the new life. */
    resetForNewPet() {
        _data = blank();
        save();
    },
};
